// <auto-generated />
using Comandas.Wf;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comandas.Wf.Migrations
{
    [DbContext(typeof(ComandasDbContext))]
    [Migration("20250829235052_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comandas.Wf.Modelos.CardapioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PossuiPreparo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CardapioItem", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer");

                    b.Property<int>("SituacaoComanda")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Comanda", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.ComandaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardapioItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardapioItemId");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComandaItem", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer");

                    b.Property<int>("SituacaoMesa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.PedidoCozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("integer");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("PedidoCozinha", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.PedidoCozinhaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoCozinhaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComandaItemId");

                    b.HasIndex("PedidoCozinhaId");

                    b.ToTable("PedidoCozinhaItem", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.ComandaItem", b =>
                {
                    b.HasOne("Comandas.Wf.Modelos.CardapioItem", "CardapioItem")
                        .WithMany()
                        .HasForeignKey("CardapioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas.Wf.Modelos.Comanda", "Comanda")
                        .WithMany("ComandaItens")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardapioItem");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.PedidoCozinha", b =>
                {
                    b.HasOne("Comandas.Wf.Modelos.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.PedidoCozinhaItem", b =>
                {
                    b.HasOne("Comandas.Wf.Modelos.ComandaItem", "ComandaItem")
                        .WithMany()
                        .HasForeignKey("ComandaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas.Wf.Modelos.PedidoCozinha", "PedidoCozinha")
                        .WithMany("PedidoCozinhaItems")
                        .HasForeignKey("PedidoCozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComandaItem");

                    b.Navigation("PedidoCozinha");
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.Comanda", b =>
                {
                    b.Navigation("ComandaItens");
                });

            modelBuilder.Entity("Comandas.Wf.Modelos.PedidoCozinha", b =>
                {
                    b.Navigation("PedidoCozinhaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
